variable "aws_region" {
  description = "AWS region to deploy resources into"
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Project name used for tagging and naming"
  type        = string
  default     = "swing-alert-bot"
}

variable "environment" {
  description = "Environment name (e.g., dev, prod)"
  type        = string
  default     = "dev"
}

// Optional: exact S3 bucket name override for state storage.
// If empty, a unique name will be generated by appending the AWS account ID.
variable "state_bucket_name" {
  description = "Override S3 bucket name for state (leave empty to auto-suffix with AWS account ID)"
  type        = string
  default     = ""
}

variable "tags" {
  description = "Extra tags to apply to all resources"
  type        = map(string)
  default     = {}
}

# Optional: secrets supplied via tfvars to create SSM parameters
variable "alpha_vantage_api_key" { type = string, default = null }
variable "telegram_bot_token"    { type = string, default = null }
variable "telegram_chat_id"      { type = string, default = null }
variable "fernet_key"            { type = string, default = null }
